# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: Project-02-Travel_Management
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: SYSTEM
    password: PASSWORD
  jpa:
    show-sql: true
server:
  port: 4041

plan:
   module:
       messages:
             save-success: Travel Plan is saved with id values
             save-failure: Travel Plan is not saved with id values
             find-by-id-failure: Travel Plan is not found
             update-success: Travel Plan is updated
             update-failure: Travel Plan is not found for updation
             delete-success: Travel Plan is deleted
             delete-failure: Travel Plan is not found for deletion
             status-change-success: Travel Plan status is changed
             stauts-change-failure: Travel Plan is not found for status change